# -------------------------------- GENERATED BY C_BUILD --------------------------------
from c_build.source.Utilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------
compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "cl"
compiler_std_version = "c11"
compiler_warning_level = ""
compiler_disable_specific_warnings = []
compiler_treat_warnings_as_errors = True

if not IS_WINDOWS():
    compiler_name = "gcc"

project_name = "OpenGL_TechDemo"
project_dependencies = ["ckit"]
project_rebuild_project_dependencies = False
project_debug_with_visual_studio = False
project_executable_procedures = ["OpenGL_TechDemo.exe"]

if compiler_name == "cl":
    project_warning_level = "2"
    project_disable_specific_warnings = ["5105", "4668", "4820"]
elif compiler_name in ["gcc", "cc", "clang"]:
    project_warning_level = ""


ckit_lib = C_BUILD_LIB('ckit', compiler_name)
glfw_lib_path = "../Libraries/glfw/" 

if compiler_name == "cl":
    glfw_lib_path += "lib-static-ucrt/glfw3dll.lib"
else:
    glfw_lib_path += "lib-mingw-w64/libglfw3dll.a"

libs = [f"../ckit/build_{compiler_name}/{ckit_lib}"] # ckit
libs += (["Kernel32.lib", "User32.lib", "Gdi32.lib", "OpenGL32.lib", f"{glfw_lib_path}"] if compiler_name == "cl" 
         else ["-lUser32", "-lGdi32", "-lopengl32", f"{glfw_lib_path}"]) # Opengl and glfw

#[] 
procedures_config = {
    "OpenGL_TechDemo": {
        "build_directory": f"./build_{compiler_name}",
        "output_name": f"OpenGL_TechDemo.exe",
        "source_files": ["../Source/*.c", "../Libraries/glad/src/glad.c"],
        "additional_libs": libs,
        "compile_time_defines": [],
        "include_paths": [
            "../Include", 
            "../ckit",
            "../Libraries",
            "../Libraries/stb",
            "../Libraries/glad/include", 
            "../Libraries/glfw",
        ],
    },
}

compiler_config = {key: value for key, value in locals().items() if key.startswith('compiler_')}
project_config = {key: value for key, value in locals().items() if key.startswith('project_')}

manager: Manager = Manager(compiler_config, project_config, procedures_config)
manager.build_project()
# -------------------------------------------------------------------------------------

