# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))
from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------s

pc: ProjectConfig = ProjectConfig(
    project_name = "OpenGL_TechDemo",
    project_dependencies = ["ckit"],
    project_debug_with_visual_studio = True,
    project_rebuild_project_dependencies = True,
    project_executable_names  = ["OpenGL_TechDemo.exe"]
)

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
    compiler_std_version = "c11",
    compiler_warning_level = "",
    compiler_disable_specific_warnings = [""],
    compiler_treat_warnings_as_errors = True,
    compiler_disable_warnings  = False,
    compiler_disable_sanitizer = True
)

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

# Do different things depending on the platform
if cc.compiler_name == "cl":
    cc.compiler_warning_level = "3"
    cc.compiler_disable_specific_warnings = ["5105", "4668", "4820", "4996"]
else:
    cc.compiler_warning_level = "all"
    cc.compiler_disable_specific_warnings = ["deprecated", "parentheses"]

ckit_lib = GET_LIB_NAME(cc, 'ckit')
glfw_lib_path = "../Libraries/glfw/" 

if cc.compiler_name == "cl":
    glfw_lib_path += "lib-static-ucrt/glfw3dll.lib"
else:
    glfw_lib_path += "lib-mingw-w64/libglfw3dll.a"

libs = [f"../ckit/build_{cc.compiler_name}/{ckit_lib}"] # ckit
libs += (["Kernel32.lib", "User32.lib", "Gdi32.lib", "OpenGL32.lib", f"{glfw_lib_path}"] if cc.compiler_name == "cl" 
         else ["-lUser32", "-lGdi32", "-lopengl32", f"{glfw_lib_path}"]) # Opengl and glfw

procedures_config = {
    "OpenGL_TechDemo": ProcedureConfig(
        build_directory = f"./build_{cc.compiler_name}",
        output_name = f"OpenGL_TechDemo.exe",
        source_files = ["../Source/*.cpp", "../Libraries/glad/src/glad.c"],
        additional_libs = libs,
        include_paths = [
            "../Include", 
            "../ckit",
            "../Libraries",
            "../Libraries/stb",
            "../Libraries/glad/include", 
            "../Libraries/glfw",
        ],
    )
}

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()
# ------------------------------------------------------------------------------------