# Unified cross-platform build script
# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))
from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------

pc: ProjectConfig = ProjectConfig(
    project_name = "OpenGL_TechDemo",
    project_dependencies = [
        Dependency(name="ckg", branch_name="CompleteRewrite"),
        Dependency(name="GameMath", branch_name="Rework"),
        Dependency(name="IOD")
    ],
    project_debug_with_visual_studio = True,
    project_rebuild_project_dependencies = False,
    project_executable_names = ["OpenGL_TechDemo.exe"]
)

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
    compiler_std_version = "",
    compiler_warning_level = "",
    compiler_disable_specific_warnings = [""],
    compiler_treat_warnings_as_errors = True,
    compiler_disable_warnings = False,
    compiler_enable_sanitizer = False
)

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

if cc.compiler_name == "cl":
    cc.compiler_warning_level = "4"
    cc.compiler_disable_specific_warnings = ["4244", "4100", "4458", "4201", "4116"]
else:
    cc.compiler_warning_level = ""
    cc.compiler_disable_specific_warnings = [
        "deprecated",
        "parentheses",
        "implicit-fallthrough",
        "unused-variable"
    ]

build_postfix = f"build_{cc.compiler_name}/{C_BUILD_BUILD_TYPE()}"
common_libs = [
    f"../../ckg/{build_postfix}/{GET_LIB_NAME(cc, 'ckg')}",
    f"../../GameMath/{build_postfix}/{GET_LIB_NAME(cc, 'gm')}",
    f"../../IOD/{build_postfix}/{GET_LIB_NAME(cc, 'IOD')}"
]

platform_libs = []
if IS_WINDOWS():
    glfw_lib = "../../Vendor/glfw/bin/windows/lib-static-ucrt/glfw3dll.lib" if cc.compiler_name == "cl" else "../../Vendor/glfw/bin/windows/glfw/lib-mingw-w64/libglfw3dll.a"
    platform_libs += [
        GET_LIB_FLAG(cc, "Kernel32"),
        GET_LIB_FLAG(cc, "User32"),
        GET_LIB_FLAG(cc, "Gdi32"),
        GET_LIB_FLAG(cc, "OpenGL32"),
        f"../../Vendor/assimp/bin/windows/{GET_LIB_NAME(cc, 'assimp-vc143-mtd')}",
        glfw_lib
    ]
elif IS_DARWIN():
    platform_libs += [
        "-framework OpenGL",
        "-framework Cocoa",
        "-framework IOKit",
        "-framework CoreFoundation",
        "../../Vendor/glfw/bin/macos/lib-arm64/libglfw3.a",
        "../../Vendor/assimp/bin/macos/libassimp.dylib"
    ]
elif IS_LINUX():
    platform_libs += [
        "-lGL", "-lglfw", "-lassimp"
    ]

libs = common_libs + platform_libs

source_files = [
    "../../Source/**/*.cpp",
    "../../Vendor/glad/src/glad.c"
]

include_paths = [
    "../../Include", 
    "../../Include/Loader",
    "../../Include/ShaderPrograms",
    "../../ckg",
    "../../GameMath",
    "../../IOD",
    "../../Vendor",
    "../../Vendor/stb",
    "../../Vendor/glad/include", 
    "../../Vendor/glfw",
    "../../Vendor/assimp/include",
]

procedures_config = {
    "OpenGL_TechDemo": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = "OpenGL_TechDemo.exe",
        source_files = source_files,
        additional_libs = libs,
        include_paths = include_paths,
        compiler_inject_into_args=[
            "-Wl,-rpath,@executable_path" if IS_DARWIN() else ""
        ]
    )
}

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()
